name: Build

on: push

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Cache Gradle data
        uses: actions/cache@v3
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle--${{ hashFiles('**/settings.gradle', '**/gradle.properties') }}

      - name: Delete empty files
        run: find $(git ls-files -m) -size 0 -delete

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildDependents
